### ISSUE TITLE
reconnect_after_disconnect test random fail.

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#139]
https://github.com/starcoinorg/starcoin/runs/567389125

---- protocol::generic_proto::tests::reconnect_after_disconnect stdout ----
thread 'protocol::generic_proto::tests::reconnect_after_disconnect' panicked at 'explicit panic', network-p2p/src/protocol/generic_proto/tests.rs:404:57
stack backtrace:
   0:     0x556ca25cdff4 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x556ca25cdff4 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x556ca25cdff4 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x556ca25cdff4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x556ca25f26cc - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x556ca1c3ac25 - std::io::Write::write_fmt::h0925d1b2b49a7c6d
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/io/mod.rs:1426
   6:     0x556ca25c4161 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h8750380b9d499e97
                               at src/libstd/io/impls.rs:156
   7:     0x556ca25d0975 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   8:     0x556ca25d0975 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49

**Comment by jolestar** [comment]
---- service_test::tests::test_notify stdout ----
thread 'service_test::tests::test_notify' panicked at 'explicit panic', <::std::macros::panic macros>:2:4
stack backtrace:
   0:     0x5582fb098084 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x5582fb098084 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x5582fb098084 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x5582fb098084 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5582fb0bc75c - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x5582fa6bfa55 - std::io::Write::write_fmt::h0925d1b2b49a7c6d
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/io/mod.rs:1426
   6:     0x5582fb08e061 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h8750380b9d499e97
                               at src/libstd/io/impls.rs:156
   7:     0x5582fb09aa05 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   8:     0x5582fb09aa05 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   9:     0x5582fb09aa05 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
  10:     0x5582fb09a698 - std::panicking::default_hook::h7a68887d113f8029
