### ISSUE TITLE
network peer info persistence panic

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#235]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: The same bootnode (`/ip6/::1/tcp/9840`) is registered with two different peer ids: `QmfUinYHHcvfL5YU4poCJMW87ChW4EEzzw1HKW2RYUaCtC` and `QmcGWAtShX1QWfy82GSyK7MFVrAX4FTbQn5XPW4emmTuTH`', network/src/net.rs:45:22
stack backtrace:
   0:        0x110e2f235 - backtrace::backtrace::libunwind::trace::h5c84db184dbe55ed
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:        0x110e2f235 - backtrace::backtrace::trace_unsynchronized::hfabf504f184a4062
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:        0x110e2f235 - std::sys_common::backtrace::_print_fmt::hb18545a457444b58
                               at src/libstd/sys_common/backtrace.rs:77
   3:        0x110e2f235 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff7732c2e44ef8b9
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x110e4f88d - core::fmt::write::hd42cb3dea57bae40
                               at src/libcore/fmt/mod.rs:1052
   5:        0x110e27c5b - std::io::Write::write_fmt::ha39f6009af02b1d2
                               at src/libstd/io/mod.rs:1426
   6:        0x110e3163a - std::sys_common::backtrace::_print::h5cfb8cdd320f1e64
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x110e3163a - std::sys_common::backtrace::print::hef683e3bc77ce269
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x110e3163a - std::panicking::default_hook::{{closure}}::h389f076017b5df43
                               at src/libstd/panicking.rs:204
   9:        0x110e3133a - std::panicking::default_hook::h04b06ec20c41bf02
                               at src/libstd/panicking.rs:224
  10:        0x110e31c8d - std::panicking::rust_panic_with_hook::hccde7faed9a5c398
                               at src/libstd/panicking.rs:472
  11:        0x110e31852 - rust_begin_unwind
                               at src/libstd/panicking.rs:380

**Comment by jolestar** [comment]
VfdwzUWDhWmctv1bgnZXRqZpcu1q", "/ip4/127.0.0.1/tcp/9840/p2p/QmQQqZHHnYL5x2iZEcMwTHPLeKPsTcoB6XEtvwtjqUQgsk", "/ip4/127.0.0.1/tcp/9840/p2p/QmfUinYHHcvfL5YU4poCJMW87ChW4EEzzw1HKW2RYUaCtC"]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: The same bootnode (`/ip4/127.0.0.1/tcp/9840`) is registered with two different peer ids: `QmfUinYHHcvfL5YU4poCJMW87ChW4EEzzw1HKW2RYUaCtC` and `QmQQqZHHnYL5x2iZEcMwTHPLeKPsTcoB6XEtvwtjqUQgsk`', network/src/net.rs:45:22
stack backtrace:
   0:        0x10a922135 - backtrace::backtrace::libunwind::trace::h5c84db184dbe55ed
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:        0x10a922135 - backtrace::backtrace::trace_unsynchronized::hfabf504f184a4062
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:        0x10a922135 - std::sys_common::backtrace::_print_fmt::hb18545a457444b58
                               at src/libstd/sys_common/backtrace.rs:77
   3:        0x10a922135 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff7732c2e44ef8b9
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x10a94278d - core::fmt::write::hd42cb3dea57bae40
