### ISSUE TITLE
The move code cannot pass move cfgir compilation.

### ISSUE THREAD

**Issue by lerencao** [starcoinorg/starcoin#2410]
``` move
address 0xA550C18 {
    module StarcoinVerifier {
        use 0x1::Vector;
        use 0x1::BCS;
        use 0xA550C18::Bit;
        use 0xA550C18::StructuredHash;

        struct StarcoinMerkle has key {
            merkle_root: vector<u8>,
        }
        const HASH_LEN_IN_BIT: u64 = 32 * 8;
        const SparseMerkleLeafNode: vector<u8> = b"SparseMerkleLeafNode";
        const SparseMerkleInternalNode: vector<u8> = b"SparseMerkleInternalNode";
        public fun create(signer: &signer, merkle_root: vector<u8>) {
            let s = StarcoinMerkle {
                merkle_root
            };
            move_to(signer, s);
        }
        struct Node has store {
            hash1: vector<u8>,
            hash2: vector<u8>,
        }
        public fun verify_on(merkle_address: address, account_address: vector<u8>, account_state_root_hash: vector<u8>, proofs: &vector<vector<u8>>): bool
        acquires StarcoinMerkle  {
            let merkle = borrow_global<StarcoinMerkle>(merkle_address);

            verify(&merkle.merkle_root, account_address, account_state_root_hash, proofs)
        }

        public fun verify(expected_root: &vector<u8>, account_address: vector<u8>, account_state_root_hash: vector<u8>, proofs: &vector<vector<u8>>): bool {

            let leaf_node = BCS::to_bytes(&Node { hash1: account_address, hash2: account_state_root_hash});
            let structure = SparseMerkleLeafNode;
            let current_hash = StructuredHash::hash(structure, leaf_node);
            let i = 0;
            let proof_length = Vector::length(proofs);
            while (i < proof_length) {
                let sibling = *Vector::borrow(proofs, i);
                let bit = Bit::get_bit(&account_address, proof_length - i - 1);
                if (bit) {
                    let internal_node = BCS::to_bytes(&Node {hash1: sibling, hash2: current_hash});
                    let structure = SparseMerkleInternalNode;
                    current_hash = StructuredHash::hash(structure, internal_node);
                } else {
                    let internal_node = BCS::to_bytes(&Node {hash1: current_hash, hash2: sibling});
                    current_hash = StructuredHash::hash(structure, internal_node);
                };
                i = i+1;
            };
            &current_hash == expected_root
        }
    }

    module StructuredHash {
        use 0x1::Hash;
        use 0x1::Vector;
        const STARCOIN_HASH_PREFIX: vector<u8> = b"STARCOIN::";
        public fun hash(structure: vector<u8>, data: vector<u8>): vector<u8> {
            let prefix_hash = Hash::sha3_256(concat(&STARCOIN_HASH_PREFIX, structure));
            Hash::sha3_256(concat(&prefix_hash, data))
        }

        fun concat(v1: &vector<u8>, v2: vector<u8>): vector<u8> {
            let data = *v1;
            Vector::append(&mut data, v2);
            data
        }

    }
    module Bit {
        use 0x1::Vector;
        public fun get_bit(data: &vector<u8>, index: u64): bool {
            let pos = index / 8;
            let bit = (7 - index % 8);
            (*Vector::borrow(data, pos) >> (bit as u8)) & 1u8 != 0
        }
    }
}
```

move compiler panics:

```
details: panicked at 'ICE invalid assign tmp local', /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/locals/mod.rs:211:48
backtrace:    0:        0x1144bceaa - backtrace::backtrace::libunwind::trace::h3c66d9aa5bd93f0f
                               at /Users/annali007/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/libunwind.rs:90:5
                           backtrace::backtrace::trace_unsynchronized::h613beb23c2487169
                               at /Users/annali007/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/mod.rs:66:5
   1:        0x1144bce38 - backtrace::backtrace::trace::h8b0ec58943e6e3c3
                               at /Users/annali007/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/mod.rs:53:14
   2:        0x1144a2cea - backtrace::capture::Backtrace::create::h11ffcc2a103d47e4
                               at /Users/annali007/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/capture.rs:176:9
   3:        0x1144a2c1f - backtrace::capture::Backtrace::new::haf933ccfe503fcf8
                               at /Users/annali007/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/capture.rs:140:22
   4:        0x11001b8f3 - starcoin_node::crash_handler::handle_panic::h1bc500d04c54402e
                               at /Users/annali007/projects/starcoinorg/starcoin/node/src/crash_handler.rs:21:38
   5:        0x10fe151f8 - starcoin_node::crash_handler::setup_panic_handler::{{closure}}::h77b821a39ad2448b
                               at /Users/annali007/projects/starcoinorg/starcoin/node/src/crash_handler.rs:14:9
   6:        0x11478bdce - std::panicking::rust_panic_with_hook::h28bf9d6c3916221e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:595:17
   7:        0x1143f7be7 - std::panicking::begin_panic::{{closure}}::ha244da0a32edaa26
                               at /Users/annali007/.rustup/toolchains/1.50.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:520:9
   8:        0x1143cc988 - std::sys_common::backtrace::__rust_end_short_backtrace::hc4c4a6dbfa3a1ed0
                               at /Users/annali007/.rustup/toolchains/1.50.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:141:18
   9:        0x1147dc607 - std::panicking::begin_panic::he711d5d7e50388b4
                               at /Users/annali007/.rustup/toolchains/1.50.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
  10:        0x1127d5e55 - move_lang::cfgir::locals::lvalue::h9d4735aa0616f1b3
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/locals/mod.rs:211:48
  11:        0x1127d5acb - move_lang::cfgir::locals::lvalues::{{closure}}::h8deefc4f659e3143
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/locals/mod.rs:188:28
  12:        0x1127ced8e - <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each::h21758c7ccc9f57de
                               at /Users/annali007/.rustup/toolchains/1.50.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:203:21
  13:        0x1127d5aa0 - move_lang::cfgir::locals::lvalues::hffd50b6d28e4fa8f
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/locals/mod.rs:188:5
  14:        0x1127d4c11 - move_lang::cfgir::locals::command::h0a895e2a2348ee62
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/locals/mod.rs:132:13
  15:        0x1127d4861 - <move_lang::cfgir::locals::LocalsSafety as move_lang::cfgir::absint::TransferFunctions>::execute::h213e69f8264cd7dc
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/locals/mod.rs:101:9
  16:        0x1127d3f16 - move_lang::cfgir::absint::AbstractInterpreter::execute_block::hea0a6557f30f27e4
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/absint.rs:153:32
  17:        0x1127d3859 - move_lang::cfgir::absint::AbstractInterpreter::analyze_function::hd23621486bf1ecf9
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/absint.rs:103:40
  18:        0x1127d4a21 - move_lang::cfgir::locals::verify::h01e33635055ad8dd
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/locals/mod.rs:118:33
  19:        0x112388e91 - move_lang::cfgir::refine_inference_and_verify::h1f69a0bb4a139834
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/mod.rs:38:25
  20:        0x11262dd4b - move_lang::cfgir::translate::function_body::hfdead9debcd486d7
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/translate.rs:396:13
  21:        0x11262d42d - move_lang::cfgir::translate::function::ha8b166fc607a6d03
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/translate.rs:359:16
  22:        0x11262b61e - move_lang::cfgir::translate::module::{{closure}}::h1152f575cd98334f
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/cfgir/translate.rs:195:46
  23:        0x11280ed2d - move_lang::shared::unique_map::UniqueMap<K,V>::map::{{closure}}::hb5ce7e8bbe0e21e4
                               at /Users/annali007/.cargo/git/checkouts/diem-5aa6d6b8b0487904/f71f37c/language/move-lang/src/shared/unique_map.rs:86:30
  24:        0x11240aafa - core::iter::adapters::map::map_fold::{{closure}}::h3ce093a0992442f3
```

**Comment by lerencao** [comment]
@jolestar @guangyuz  有空的话，也帮忙帮忙分析下是不是 move 的 bug。

**Comment by lerencao** [comment]
问题出在 verify 方法里面。但一直没看出来哪里又问题。

**Comment by lerencao** [comment]
复现命令: `dev compile StarcoinVerifier.move`

**Comment by guangyuz** [comment]
need add 'drop' ability for Node. but why the detailed message is not report? we need further study.

let vstr = match display_var(v.value()) {
                            DisplayVar::Tmp => panic!("ICE invalid assign tmp local"),
                            DisplayVar::Orig(s) => s,
                        };
                        let msg = format!(
                            "The local {} a value due to this assignment. The value does not have \
                             the '{}' ability and must be used before you assign to this local \
                             again",
                            verb,
                            Ability_::Drop,
                        );
                        let mut error = vec![
                            (*loc, format!("Invalid assignment to local '{}'", vstr)),
                            (available, msg),
                        ];
