### ISSUE TITLE
move-package-manager panicked in spectest command

### ISSUE THREAD

**Issue by zhutoulala** [starcoinorg/starcoin#3229]
It's seen on both Mac and Linux. Perhaps coming from https://github.com/starcoinorg/starcoin/blob/95e2ed2a953ef88150c4b8c7d32f5af5c16e785b/vm/move-package-manager/src/lib.rs#L22

```
thread 'main' panicked at 'Argument long must be unique

        --test is already in use', /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.34.0/src/app/parser.rs:183:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:460:5
   2: clap::app::parser::Parser::debug_asserts
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.34.0/src/app/parser.rs:183:13
   3: clap::app::parser::Parser::add_arg_ref
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.34.0/src/app/parser.rs:324:23
   4: clap::app::parser::Parser::propagate_globals
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.34.0/src/app/parser.rs:677:21
   5: clap::app::App::get_matches_from_safe_borrow
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.34.0/src/app/mod.rs:1611:13
   6: clap::app::App::get_matches_from
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.34.0/src/app/mod.rs:1522:9
   7: clap::app::App::get_matches
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.34.0/src/app/mod.rs:1463:9
   8: structopt::StructOpt::from_args
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/structopt-0.3.26/src/lib.rs:1147:26
   9: mpm::main
             at /mnt/c/Users/peter/bash/starcoin/vm/move-package-manager/src/main.rs:70:28
  10: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5```

**Comment by jolestar** [comment]
`--test` option is repeat in `move_args.build_config.test_mode` `cmd.transactionalTest.test_opts.test`, should we keep which one? @lerencao
