### ISSUE TITLE
network test  panic by accident

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#91]
thread 'protocol::generic_proto::tests::reconnect_after_disconnect' panicked at 'explicit panic', network-p2p/src/protocol/generic_proto/tests.rs:404:57
stack backtrace:
   0:     0x5568c20028e4 - backtrace::backtrace::libunwind::trace::heb43798aede8bd30
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x5568c20028e4 - backtrace::backtrace::trace_unsynchronized::had2ba7dec4bd2732
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x5568c20028e4 - std::sys_common::backtrace::_print_fmt::hda61f46e822731b2
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x5568c20028e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfe37fa5de6572965
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x5568c2028e0c - core::fmt::write::h74887d18db27282c
                               at src/libcore/fmt/mod.rs:1025
   5:     0x5568c1686005 - std::io::Write::write_fmt::h614a83dae7f00217
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/io/mod.rs:1426
   6:     0x5568c1ff9d11 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h6085952b68669738

Poll::Ready(Some(GenericProtoOut::CustomProtocolClosed { .. })) => {
                    match service2_state {
                        ServiceState::FirstConnec => service2_state = ServiceState::Disconnected,
                        ServiceState::ConnectedAgain
                        | ServiceState::NotConnected
                        | ServiceState::Disconnected => panic!(),
                    }
                }

**Comment by jolestar** [comment]
repeat with #139
